(switch_on instrument8 satellite2)
(turn_to satellite0 phenomenon5 phenomenon8)
(turn_to satellite2 groundstation0 phenomenon5)
(calibrate satellite2 instrument8 groundstation0)
(turn_to satellite2 star3 groundstation0)
(take_image satellite2 star3 instrument8 thermograph0)
(turn_to satellite2 phenomenon8 star3)
(take_image satellite2 phenomenon8 instrument8 image2)
(turn_to satellite2 star7 phenomenon8)
(take_image satellite2 star7 instrument8 thermograph0)
(turn_to satellite2 planet9 star7)
(take_image satellite2 planet9 instrument8 spectrograph1)
(turn_to satellite2 phenomenon6 planet9)
(take_image satellite2 phenomenon6 instrument8 image2)
(turn_to satellite2 phenomenon5 phenomenon6)
(take_image satellite2 phenomenon5 instrument8 image2)
