(calibrate rover2 camera0 objective1 waypoint6)
(navigate rover2 waypoint6 waypoint0)
(sample_soil rover0 rover0store waypoint7)
(communicate_soil_data rover0 general waypoint7 waypoint7 waypoint2)
(drop rover0 rover0store)
(navigate rover0 waypoint7 waypoint2)
(sample_soil rover0 rover0store waypoint2)
(navigate rover0 waypoint2 waypoint4)
(communicate_soil_data rover0 general waypoint2 waypoint4 waypoint2)
(take_image rover2 waypoint0 objective1 camera0 high_res)
(communicate_image_data rover2 general objective1 high_res waypoint0 waypoint2)
(calibrate rover2 camera0 objective1 waypoint0)
(take_image rover2 waypoint0 objective2 camera0 high_res)
(communicate_image_data rover2 general objective2 high_res waypoint0 waypoint2)
(calibrate rover2 camera0 objective1 waypoint0)
(take_image rover2 waypoint0 objective3 camera0 high_res)
(communicate_image_data rover2 general objective3 high_res waypoint0 waypoint2)
(navigate rover2 waypoint0 waypoint1)
(drop rover0 rover0store)
(sample_soil rover0 rover0store waypoint4)
(communicate_soil_data rover0 general waypoint4 waypoint4 waypoint2)
(sample_rock rover2 rover2store waypoint1)
(communicate_rock_data rover2 general waypoint1 waypoint1 waypoint2)
(drop rover2 rover2store)
(navigate rover2 waypoint1 waypoint0)
(navigate rover2 waypoint0 waypoint4)
(sample_rock rover2 rover2store waypoint4)
(communicate_rock_data rover2 general waypoint4 waypoint4 waypoint2)
(drop rover2 rover2store)
(navigate rover2 waypoint4 waypoint0)
(navigate rover2 waypoint0 waypoint6)
(navigate rover2 waypoint6 waypoint7)
(sample_rock rover2 rover2store waypoint7)
(communicate_rock_data rover2 general waypoint7 waypoint7 waypoint2)
(drop rover2 rover2store)
(navigate rover2 waypoint7 waypoint6)
(navigate rover3 waypoint3 waypoint5)
(sample_soil rover3 rover3store waypoint5)
(communicate_soil_data rover3 general waypoint5 waypoint5 waypoint2)
(sample_rock rover2 rover2store waypoint6)
(communicate_rock_data rover2 general waypoint6 waypoint6 waypoint2)
(drop rover2 rover2store)
(navigate rover2 waypoint6 waypoint2)
(navigate rover2 waypoint2 waypoint8)
(sample_rock rover2 rover2store waypoint8)
(communicate_rock_data rover2 general waypoint8 waypoint8 waypoint2)
