(calibrate rover3 camera1 objective2 waypoint13)
(calibrate rover4 camera0 objective2 waypoint1)
(navigate rover3 waypoint13 waypoint0)
(navigate rover4 waypoint1 waypoint0)
(navigate rover4 waypoint0 waypoint3)
(take_image rover4 waypoint3 objective2 camera0 low_res)
(communicate_image_data rover4 general objective2 low_res waypoint3 waypoint13)
(navigate rover0 waypoint12 waypoint0)
(sample_rock rover4 rover4store waypoint3)
(communicate_rock_data rover4 general waypoint3 waypoint3 waypoint13)
(navigate rover0 waypoint0 waypoint12)
(sample_rock rover0 rover0store waypoint12)
(navigate rover0 waypoint12 waypoint0)
(communicate_rock_data rover0 general waypoint12 waypoint0 waypoint13)
(take_image rover3 waypoint0 objective2 camera1 colour)
(calibrate rover3 camera1 objective2 waypoint0)
(communicate_image_data rover3 general objective2 colour waypoint0 waypoint13)
(take_image rover3 waypoint0 objective3 camera1 colour)
(calibrate rover3 camera1 objective2 waypoint0)
(communicate_image_data rover3 general objective3 colour waypoint0 waypoint13)
(take_image rover3 waypoint0 objective4 camera1 colour)
(communicate_image_data rover3 general objective4 colour waypoint0 waypoint13)
(calibrate rover3 camera3 objective5 waypoint0)
(take_image rover3 waypoint0 objective5 camera3 colour)
(communicate_image_data rover3 general objective5 colour waypoint0 waypoint13)
(navigate rover3 waypoint0 waypoint13)
(navigate rover3 waypoint13 waypoint5)
(sample_soil rover3 rover3store waypoint5)
(communicate_soil_data rover3 general waypoint5 waypoint5 waypoint13)
(drop rover3 rover3store)
(navigate rover3 waypoint5 waypoint14)
(sample_soil rover3 rover3store waypoint14)
(navigate rover3 waypoint14 waypoint5)
(communicate_soil_data rover3 general waypoint14 waypoint5 waypoint13)
(drop rover3 rover3store)
(navigate rover3 waypoint5 waypoint2)
(sample_soil rover3 rover3store waypoint2)
(drop rover3 rover3store)
(navigate rover3 waypoint2 waypoint5)
(communicate_soil_data rover3 general waypoint2 waypoint5 waypoint13)
(navigate rover3 waypoint5 waypoint13)
(navigate rover3 waypoint13 waypoint3)
(navigate rover5 waypoint8 waypoint5)
(sample_soil rover3 rover3store waypoint3)
(communicate_soil_data rover3 general waypoint3 waypoint3 waypoint13)
(sample_rock rover5 rover5store waypoint5)
(communicate_rock_data rover5 general waypoint5 waypoint5 waypoint13)
(drop rover5 rover5store)
(navigate rover5 waypoint5 waypoint8)
(navigate rover5 waypoint8 waypoint9)
(sample_rock rover5 rover5store waypoint9)
(navigate rover5 waypoint9 waypoint8)
(navigate rover5 waypoint8 waypoint5)
(communicate_rock_data rover5 general waypoint9 waypoint5 waypoint13)
