(switch_on instrument1 satellite1)
(switch_on instrument0 satellite0)
(switch_on instrument10 satellite4)
(switch_on instrument14 satellite6)
(turn_to satellite0 groundstation0 planet5)
(calibrate satellite0 instrument0 groundstation0)
(switch_on instrument4 satellite2)
(turn_to satellite0 phenomenon23 groundstation0)
(take_image satellite0 phenomenon23 instrument0 infrared3)
(turn_to satellite0 phenomenon24 phenomenon23)
(take_image satellite0 phenomenon24 instrument0 infrared3)
(turn_to satellite0 planet13 phenomenon24)
(take_image satellite0 planet13 instrument0 infrared3)
(turn_to satellite2 groundstation2 star21)
(calibrate satellite2 instrument4 groundstation2)
(turn_to satellite1 star22 planet5)
(turn_to satellite2 phenomenon14 groundstation2)
(take_image satellite2 phenomenon14 instrument4 infrared2)
(turn_to satellite2 phenomenon15 phenomenon14)
(take_image satellite2 phenomenon15 instrument4 infrared2)
(turn_to satellite2 phenomenon17 phenomenon15)
(take_image satellite2 phenomenon17 instrument4 thermograph1)
(turn_to satellite2 planet12 phenomenon17)
(take_image satellite2 planet12 instrument4 thermograph1)
(turn_to satellite2 planet16 planet12)
(take_image satellite2 planet16 instrument4 infrared2)
(turn_to satellite2 star10 planet16)
(take_image satellite2 star10 instrument4 thermograph1)
(turn_to satellite2 star21 star10)
(take_image satellite2 star21 instrument4 thermograph1)
(turn_to satellite8 planet16 phenomenon23)
(turn_to satellite4 star3 star22)
(calibrate satellite4 instrument10 star3)
(turn_to satellite4 phenomenon20 star3)
(turn_to satellite4 phenomenon9 phenomenon20)
(take_image satellite4 phenomenon9 instrument10 image4)
(turn_to satellite4 phenomenon20 phenomenon9)
(turn_to satellite4 planet11 phenomenon20)
(take_image satellite4 planet11 instrument10 image4)
(turn_to satellite4 phenomenon20 planet11)
(turn_to satellite4 planet5 phenomenon20)
(take_image satellite4 planet5 instrument10 image0)
(turn_to satellite4 phenomenon20 planet5)
(turn_to satellite4 planet6 phenomenon20)
(take_image satellite4 planet6 instrument10 image4)
(turn_to satellite4 phenomenon20 planet6)
(turn_to satellite4 planet7 phenomenon20)
(take_image satellite4 planet7 instrument10 image4)
(turn_to satellite4 phenomenon20 planet7)
(turn_to satellite4 star18 phenomenon20)
(take_image satellite4 star18 instrument10 image4)
(turn_to satellite4 phenomenon20 star18)
(turn_to satellite4 star22 phenomenon20)
(take_image satellite4 star22 instrument10 image4)
(turn_to satellite4 phenomenon20 star22)
