(switch_on instrument1 satellite1)
(calibrate satellite1 instrument1 groundstation3)
(switch_on instrument5 satellite2)
(switch_on instrument7 satellite3)
(turn_to satellite0 phenomenon9 star8)
(turn_to satellite1 phenomenon15 groundstation3)
(take_image satellite1 phenomenon15 instrument1 infrared0)
(turn_to satellite1 phenomenon7 phenomenon15)
(take_image satellite1 phenomenon7 instrument1 infrared1)
(turn_to satellite1 planet6 phenomenon7)
(take_image satellite1 planet6 instrument1 infrared1)
(turn_to satellite1 star11 planet6)
(take_image satellite1 star11 instrument1 infrared1)
(turn_to satellite1 star17 star11)
(take_image satellite1 star17 instrument1 infrared0)
(turn_to satellite1 star4 star17)
(turn_to satellite2 planet13 star4)
(turn_to satellite3 planet16 phenomenon9)
(turn_to satellite4 star11 phenomenon9)
(turn_to satellite2 star0 planet13)
(calibrate satellite2 instrument5 star0)
(turn_to satellite2 planet13 star0)
(take_image satellite2 planet13 instrument5 spectrograph4)
(turn_to satellite2 planet14 planet13)
(take_image satellite2 planet14 instrument5 thermograph2)
(turn_to satellite2 star10 planet14)
(take_image satellite2 star10 instrument5 thermograph2)
(turn_to satellite3 star2 planet16)
(calibrate satellite3 instrument7 star2)
(turn_to satellite3 planet16 star2)
(take_image satellite3 planet16 instrument7 image3)
(turn_to satellite3 star5 planet16)
(take_image satellite3 star5 instrument7 image3)
(turn_to satellite3 star8 star5)
(take_image satellite3 star8 instrument7 image3)
