(switch_on instrument2 satellite0)
(switch_on instrument3 satellite1)
(turn_to satellite0 groundstation0 phenomenon8)
(calibrate satellite0 instrument2 groundstation0)
(turn_to satellite0 phenomenon5 groundstation0)
(take_image satellite0 phenomenon5 instrument2 image2)
(turn_to satellite0 phenomenon6 phenomenon5)
(take_image satellite0 phenomenon6 instrument2 image2)
(turn_to satellite0 phenomenon5 phenomenon6)
(turn_to satellite0 phenomenon8 phenomenon5)
(take_image satellite0 phenomenon8 instrument2 image2)
(turn_to satellite0 phenomenon5 phenomenon8)
(turn_to satellite1 groundstation0 groundstation2)
(calibrate satellite1 instrument3 groundstation0)
(turn_to satellite1 groundstation2 groundstation0)
(turn_to satellite1 planet9 groundstation2)
(take_image satellite1 planet9 instrument3 spectrograph1)
(turn_to satellite1 groundstation2 planet9)
(turn_to satellite1 star3 groundstation2)
(take_image satellite1 star3 instrument3 thermograph0)
(turn_to satellite1 groundstation2 star3)
(turn_to satellite1 star7 groundstation2)
(take_image satellite1 star7 instrument3 thermograph0)
(turn_to satellite1 groundstation2 star7)
