(switch_on instrument1 satellite0)
(switch_on instrument3 satellite1)
(switch_on instrument4 satellite2)
(turn_to satellite0 groundstation0 star6)
(calibrate satellite0 instrument1 groundstation0)
(turn_to satellite0 planet9 groundstation0)
(take_image satellite0 planet9 instrument1 image3)
(turn_to satellite1 planet11 groundstation0)
(turn_to satellite2 star1 star6)
(calibrate satellite2 instrument4 star1)
(turn_to satellite2 phenomenon5 star1)
(take_image satellite2 phenomenon5 instrument4 image0)
(turn_to satellite1 groundstation4 planet11)
(calibrate satellite1 instrument3 groundstation4)
(turn_to satellite1 planet11 groundstation4)
(take_image satellite1 planet11 instrument3 image2)
(turn_to satellite1 star1 planet11)
(turn_to satellite1 planet8 star1)
(take_image satellite1 planet8 instrument3 image0)
(turn_to satellite1 star1 planet8)
(turn_to satellite1 star7 star1)
(take_image satellite1 star7 instrument3 image0)
(turn_to satellite1 star1 star7)
(turn_to satellite2 planet10 phenomenon5)
(take_image satellite2 planet10 instrument4 image0)
(turn_to satellite2 phenomenon5 planet10)
(turn_to satellite2 star6 phenomenon5)
(take_image satellite2 star6 instrument4 image1)
(turn_to satellite2 phenomenon5 star6)
