(switch_on instrument0 satellite0)
(switch_on instrument3 satellite1)
(calibrate satellite1 instrument3 star4)
(switch_on instrument7 satellite4)
(turn_to satellite4 planet11 star14)
(turn_to satellite4 star2 planet11)
(calibrate satellite4 instrument7 star2)
(turn_to satellite4 planet11 star2)
(take_image satellite4 planet11 instrument7 infrared3)
(turn_to satellite4 planet16 planet11)
(take_image satellite4 planet16 instrument7 infrared1)
(turn_to satellite4 planet8 planet16)
(take_image satellite4 planet8 instrument7 infrared1)
(turn_to satellite4 star15 planet8)
(take_image satellite4 star15 instrument7 infrared3)
(turn_to satellite4 star22 star15)
(take_image satellite4 star22 instrument7 infrared1)
(turn_to satellite1 phenomenon13 star4)
(take_image satellite1 phenomenon13 instrument3 spectrograph4)
(turn_to satellite1 phenomenon17 phenomenon13)
(take_image satellite1 phenomenon17 instrument3 spectrograph4)
(turn_to satellite1 phenomenon21 phenomenon17)
(turn_to satellite1 phenomenon24 phenomenon21)
(take_image satellite1 phenomenon24 instrument3 infrared0)
(turn_to satellite1 phenomenon21 phenomenon24)
(turn_to satellite1 phenomenon6 phenomenon21)
(take_image satellite1 phenomenon6 instrument3 spectrograph4)
(turn_to satellite1 phenomenon21 phenomenon6)
(turn_to satellite1 planet5 phenomenon21)
(take_image satellite1 planet5 instrument3 infrared0)
(turn_to satellite1 phenomenon21 planet5)
(turn_to satellite1 star18 phenomenon21)
(take_image satellite1 star18 instrument3 spectrograph4)
(turn_to satellite1 phenomenon21 star18)
(turn_to satellite1 star23 phenomenon21)
(take_image satellite1 star23 instrument3 spectrograph4)
(turn_to satellite1 phenomenon21 star23)
(turn_to satellite1 star7 phenomenon21)
(take_image satellite1 star7 instrument3 infrared0)
(turn_to satellite1 phenomenon21 star7)
(turn_to satellite1 star9 phenomenon21)
(take_image satellite1 star9 instrument3 spectrograph4)
(switch_off instrument3 satellite1)
(switch_on instrument4 satellite1)
(turn_to satellite1 phenomenon21 star9)
(turn_to satellite1 star4 phenomenon21)
(calibrate satellite1 instrument4 star4)
(turn_to satellite1 phenomenon21 star4)
(take_image satellite1 phenomenon21 instrument4 thermograph2)
(turn_to satellite1 planet10 phenomenon21)
(take_image satellite1 planet10 instrument4 thermograph2)
(turn_to satellite1 planet20 planet10)
(take_image satellite1 planet20 instrument4 thermograph2)
(turn_to satellite1 star14 planet20)
(take_image satellite1 star14 instrument4 thermograph2)
(turn_to satellite1 star19 star14)
(take_image satellite1 star19 instrument4 thermograph2)
