(calibrate rover1 camera3 objective0 waypoint4)
(navigate rover0 waypoint1 waypoint2)
(navigate rover0 waypoint2 waypoint3)
(sample_soil rover0 rover0store waypoint3)
(communicate_soil_data rover0 general waypoint3 waypoint3 waypoint7)
(calibrate rover0 camera4 objective3 waypoint3)
(take_image rover0 waypoint3 objective2 camera4 low_res)
(communicate_image_data rover0 general objective2 low_res waypoint3 waypoint7)
(take_image rover1 waypoint4 objective0 camera3 colour)
(calibrate rover1 camera3 objective0 waypoint4)
(take_image rover1 waypoint4 objective0 camera3 low_res)
(sample_rock rover1 rover1store waypoint4)
(drop rover1 rover1store)
(navigate rover1 waypoint4 waypoint5)
(communicate_image_data rover1 general objective0 colour waypoint5 waypoint7)
(communicate_rock_data rover1 general waypoint4 waypoint5 waypoint7)
(communicate_image_data rover1 general objective0 low_res waypoint5 waypoint7)
(sample_rock rover1 rover1store waypoint5)
(drop rover1 rover1store)
(communicate_rock_data rover1 general waypoint5 waypoint5 waypoint7)
(navigate rover1 waypoint5 waypoint4)
(navigate rover1 waypoint4 waypoint6)
(sample_soil rover1 rover1store waypoint6)
(drop rover1 rover1store)
(navigate rover1 waypoint6 waypoint8)
(communicate_soil_data rover1 general waypoint6 waypoint8 waypoint7)
(sample_rock rover1 rover1store waypoint8)
(communicate_rock_data rover1 general waypoint8 waypoint8 waypoint7)
