(calibrate rover1 camera4 objective4 waypoint4)
(navigate rover0 waypoint22 waypoint11)
(navigate rover0 waypoint11 waypoint6)
(navigate rover3 waypoint3 waypoint1)
(navigate rover0 waypoint6 waypoint2)
(navigate rover2 waypoint3 waypoint18)
(navigate rover2 waypoint18 waypoint9)
(navigate rover3 waypoint1 waypoint14)
(sample_rock rover3 rover3store waypoint14)
(communicate_rock_data rover3 general waypoint14 waypoint14 waypoint1)
(navigate rover4 waypoint16 waypoint15)
(navigate rover7 waypoint16 waypoint10)
(sample_rock rover7 rover7store waypoint10)
(navigate rover7 waypoint10 waypoint15)
(communicate_rock_data rover7 general waypoint10 waypoint15 waypoint1)
(sample_rock rover2 rover2store waypoint9)
(drop rover2 rover2store)
(navigate rover2 waypoint9 waypoint18)
(communicate_rock_data rover2 general waypoint9 waypoint18 waypoint1)
(navigate rover4 waypoint15 waypoint16)
(sample_rock rover2 rover2store waypoint18)
(communicate_rock_data rover2 general waypoint18 waypoint18 waypoint1)
(sample_rock rover4 rover4store waypoint16)
(drop rover4 rover4store)
(navigate rover4 waypoint16 waypoint15)
(communicate_rock_data rover4 general waypoint16 waypoint15 waypoint1)
(drop rover2 rover2store)
(navigate rover2 waypoint18 waypoint3)
(navigate rover4 waypoint15 waypoint12)
(navigate rover6 waypoint4 waypoint13)
(drop rover3 rover3store)
(sample_rock rover4 rover4store waypoint12)
(navigate rover3 waypoint14 waypoint1)
(navigate rover3 waypoint1 waypoint23)
(sample_soil rover3 rover3store waypoint23)
(communicate_soil_data rover3 general waypoint23 waypoint23 waypoint1)
(drop rover3 rover3store)
(navigate rover3 waypoint23 waypoint1)
(navigate rover3 waypoint1 waypoint4)
(navigate rover0 waypoint2 waypoint6)
(navigate rover0 waypoint6 waypoint11)
(sample_soil rover0 rover0store waypoint11)
(navigate rover0 waypoint11 waypoint6)
(navigate rover0 waypoint6 waypoint2)
(communicate_soil_data rover0 general waypoint11 waypoint2 waypoint1)
(navigate rover2 waypoint3 waypoint13)
(navigate rover2 waypoint13 waypoint21)
(navigate rover4 waypoint12 waypoint15)
(communicate_rock_data rover4 general waypoint12 waypoint15 waypoint1)
(sample_rock rover2 rover2store waypoint21)
(drop rover2 rover2store)
(navigate rover2 waypoint21 waypoint13)
(drop rover4 rover4store)
(navigate rover2 waypoint13 waypoint3)
(communicate_rock_data rover2 general waypoint21 waypoint3 waypoint1)
(navigate rover3 waypoint4 waypoint7)
(sample_rock rover3 rover3store waypoint7)
(drop rover3 rover3store)
(navigate rover3 waypoint7 waypoint4)
(communicate_rock_data rover3 general waypoint7 waypoint4 waypoint1)
(navigate rover3 waypoint4 waypoint7)
(navigate rover6 waypoint13 waypoint4)
(sample_soil rover3 rover3store waypoint7)
(navigate rover3 waypoint7 waypoint4)
(communicate_soil_data rover3 general waypoint7 waypoint4 waypoint1)
(drop rover3 rover3store)
(navigate rover3 waypoint4 waypoint8)
(sample_soil rover3 rover3store waypoint8)
(navigate rover3 waypoint8 waypoint4)
(communicate_soil_data rover3 general waypoint8 waypoint4 waypoint1)
(navigate rover4 waypoint15 waypoint16)
(navigate rover4 waypoint16 waypoint22)
(sample_rock rover4 rover4store waypoint22)
(navigate rover4 waypoint22 waypoint16)
(navigate rover4 waypoint16 waypoint5)
(communicate_rock_data rover4 general waypoint22 waypoint5 waypoint1)
(navigate rover6 waypoint4 waypoint13)
(sample_soil rover6 rover6store waypoint13)
(drop rover6 rover6store)
(navigate rover6 waypoint13 waypoint4)
(communicate_soil_data rover6 general waypoint13 waypoint4 waypoint1)
(navigate rover6 waypoint4 waypoint20)
(sample_soil rover6 rover6store waypoint20)
(navigate rover6 waypoint20 waypoint4)
(communicate_soil_data rover6 general waypoint20 waypoint4 waypoint1)
(take_image rover1 waypoint4 objective0 camera4 high_res)
(calibrate rover4 camera2 objective0 waypoint5)
(communicate_image_data rover1 general objective0 high_res waypoint4 waypoint1)
(take_image rover4 waypoint5 objective2 camera2 high_res)
(calibrate rover4 camera2 objective0 waypoint5)
(communicate_image_data rover4 general objective2 high_res waypoint5 waypoint1)
(take_image rover4 waypoint5 objective3 camera2 colour)
(calibrate rover4 camera2 objective0 waypoint5)
(communicate_image_data rover4 general objective3 colour waypoint5 waypoint1)
(take_image rover4 waypoint5 objective5 camera2 high_res)
(communicate_image_data rover4 general objective5 high_res waypoint5 waypoint1)
(calibrate rover4 camera2 objective0 waypoint5)
(take_image rover4 waypoint5 objective7 camera2 colour)
(communicate_image_data rover4 general objective7 colour waypoint5 waypoint1)
