(switch_on instrument0 satellite0)
(switch_on instrument4 satellite1)
(switch_on instrument8 satellite2)
(turn_to satellite0 phenomenon13 star8)
(turn_to satellite0 phenomenon17 phenomenon13)
(turn_to satellite2 planet19 star4)
(turn_to satellite0 phenomenon13 phenomenon17)
(turn_to satellite2 star3 planet19)
(calibrate satellite2 instrument8 star3)
(turn_to satellite2 phenomenon13 star3)
(take_image satellite2 phenomenon13 instrument8 thermograph2)
(turn_to satellite2 phenomenon17 phenomenon13)
(take_image satellite2 phenomenon17 instrument8 thermograph4)
(turn_to satellite1 phenomenon18 phenomenon21)
(turn_to satellite2 phenomenon5 phenomenon17)
(take_image satellite2 phenomenon5 instrument8 thermograph4)
(turn_to satellite2 planet19 phenomenon5)
(take_image satellite2 planet19 instrument8 thermograph2)
(turn_to satellite2 planet20 planet19)
(take_image satellite2 planet20 instrument8 thermograph4)
(turn_to satellite2 star15 planet20)
(take_image satellite2 star15 instrument8 thermograph2)
(turn_to satellite2 star22 star15)
(take_image satellite2 star22 instrument8 thermograph3)
(turn_to satellite2 star8 star22)
(take_image satellite2 star8 instrument8 thermograph3)
(turn_to satellite1 phenomenon21 phenomenon18)
(turn_to satellite1 star1 phenomenon21)
(calibrate satellite1 instrument4 star1)
(turn_to satellite1 phenomenon18 star1)
(take_image satellite1 phenomenon18 instrument4 image1)
(turn_to satellite1 phenomenon21 phenomenon18)
(take_image satellite1 phenomenon21 instrument4 image1)
(turn_to satellite1 planet7 phenomenon21)
(take_image satellite1 planet7 instrument4 image1)
(turn_to satellite1 star10 planet7)
(take_image satellite1 star10 instrument4 image1)
(turn_to satellite1 star9 star10)
(take_image satellite1 star9 instrument4 image1)
