(switch_on instrument10 satellite1)
(switch_on instrument0 satellite0)
(switch_on instrument17 satellite2)
(switch_on instrument20 satellite3)
(turn_to satellite0 star16 groundstation1)
(switch_on instrument27 satellite4)
(switch_off instrument0 satellite0)
(switch_on instrument8 satellite0)
(turn_to satellite0 phenomenon14 star16)
(turn_to satellite0 planet18 phenomenon14)
(turn_to satellite2 phenomenon8 phenomenon14)
(turn_to satellite0 phenomenon21 planet18)
(turn_to satellite0 phenomenon5 phenomenon21)
(turn_to satellite0 phenomenon8 phenomenon5)
(turn_to satellite3 groundstation1 star10)
(calibrate satellite3 instrument20 groundstation1)
(turn_to satellite0 planet18 phenomenon8)
(turn_to satellite0 star2 planet18)
(calibrate satellite0 instrument8 star2)
(turn_to satellite0 phenomenon14 star2)
(take_image satellite0 phenomenon14 instrument8 thermograph7)
(turn_to satellite0 phenomenon21 phenomenon14)
(take_image satellite0 phenomenon21 instrument8 thermograph7)
(turn_to satellite0 phenomenon5 phenomenon21)
(take_image satellite0 phenomenon5 instrument8 spectrograph0)
(turn_to satellite0 phenomenon8 phenomenon5)
(take_image satellite0 phenomenon8 instrument8 thermograph7)
(turn_to satellite0 planet18 phenomenon8)
(take_image satellite0 planet18 instrument8 infrared9)
(take_image satellite0 planet18 instrument8 thermograph7)
(turn_to satellite0 star11 planet18)
(take_image satellite0 star11 instrument8 thermograph7)
(turn_to satellite0 star20 star11)
(take_image satellite0 star20 instrument8 spectrograph0)
(turn_to satellite0 star23 star20)
(take_image satellite0 star23 instrument8 infrared9)
(turn_to satellite0 star6 star23)
(take_image satellite0 star6 instrument8 spectrograph0)
(turn_to satellite3 phenomenon12 groundstation1)
(take_image satellite3 phenomenon12 instrument20 image4)
(turn_to satellite3 phenomenon19 phenomenon12)
(take_image satellite3 phenomenon19 instrument20 image2)
(take_image satellite3 phenomenon19 instrument20 image4)
(turn_to satellite1 phenomenon5 phenomenon19)
(turn_to satellite1 phenomenon8 phenomenon5)
(turn_to satellite3 phenomenon21 phenomenon19)
(take_image satellite3 phenomenon21 instrument20 image2)
(take_image satellite3 phenomenon21 instrument20 image4)
(turn_to satellite1 phenomenon19 phenomenon8)
(turn_to satellite1 phenomenon5 phenomenon19)
(turn_to satellite3 phenomenon5 phenomenon21)
(take_image satellite3 phenomenon5 instrument20 image3)
(turn_to satellite1 phenomenon19 phenomenon5)
(turn_to satellite1 phenomenon8 phenomenon19)
(turn_to satellite1 planet22 phenomenon8)
(turn_to satellite3 planet13 phenomenon5)
(take_image satellite3 planet13 instrument20 image2)
(turn_to satellite1 phenomenon19 planet22)
(turn_to satellite1 phenomenon5 phenomenon19)
(turn_to satellite3 planet15 planet13)
(take_image satellite3 planet15 instrument20 image3)
(turn_to satellite3 planet22 planet15)
(take_image satellite3 planet22 instrument20 image2)
(turn_to satellite1 phenomenon19 phenomenon5)
(turn_to satellite3 planet7 planet22)
(take_image satellite3 planet7 instrument20 image2)
(turn_to satellite1 phenomenon5 phenomenon19)
(turn_to satellite3 star11 planet7)
(take_image satellite3 star11 instrument20 image3)
(take_image satellite3 star11 instrument20 image4)
(turn_to satellite1 phenomenon19 phenomenon5)
(turn_to satellite1 phenomenon8 phenomenon19)
(turn_to satellite1 planet13 phenomenon8)
(turn_to satellite3 star16 star11)
(take_image satellite3 star16 instrument20 image3)
(take_image satellite3 star16 instrument20 image4)
(turn_to satellite1 phenomenon19 planet13)
(turn_to satellite1 phenomenon5 phenomenon19)
(turn_to satellite3 star23 star16)
(take_image satellite3 star23 instrument20 image2)
(turn_to satellite1 phenomenon19 phenomenon5)
(turn_to satellite1 phenomenon8 phenomenon19)
(turn_to satellite1 planet13 phenomenon8)
(turn_to satellite3 star6 star23)
(take_image satellite3 star6 instrument20 image3)
(turn_to satellite1 phenomenon19 planet13)
(turn_to satellite1 phenomenon5 phenomenon19)
(turn_to satellite1 star4 phenomenon5)
(calibrate satellite1 instrument10 star4)
(turn_to satellite1 phenomenon19 star4)
(turn_to satellite1 phenomenon5 phenomenon19)
(take_image satellite1 phenomenon5 instrument10 thermograph8)
(turn_to satellite1 phenomenon19 phenomenon5)
(turn_to satellite1 phenomenon8 phenomenon19)
(take_image satellite1 phenomenon8 instrument10 spectrograph6)
(turn_to satellite1 phenomenon19 phenomenon8)
(turn_to satellite1 planet13 phenomenon19)
(take_image satellite1 planet13 instrument10 spectrograph6)
(turn_to satellite1 phenomenon19 planet13)
(turn_to satellite1 planet22 phenomenon19)
(take_image satellite1 planet22 instrument10 spectrograph6)
(turn_to satellite1 phenomenon19 planet22)
(turn_to satellite1 planet7 phenomenon19)
(take_image satellite1 planet7 instrument10 spectrograph6)
(turn_to satellite1 phenomenon19 planet7)
(turn_to satellite1 planet9 phenomenon19)
(take_image satellite1 planet9 instrument10 spectrograph6)
(turn_to satellite1 phenomenon19 planet9)
(turn_to satellite1 star10 phenomenon19)
(take_image satellite1 star10 instrument10 spectrograph6)
(turn_to satellite1 phenomenon19 star10)
(turn_to satellite1 star24 phenomenon19)
(take_image satellite1 star24 instrument10 spectrograph6)
(turn_to satellite1 phenomenon19 star24)
(turn_to satellite1 star6 phenomenon19)
(take_image satellite1 star6 instrument10 spectrograph6)
(turn_to satellite1 phenomenon19 star6)
(turn_to satellite2 planet13 phenomenon8)
(turn_to satellite2 planet18 planet13)
(turn_to satellite2 star0 planet18)
(calibrate satellite2 instrument17 star0)
(turn_to satellite2 phenomenon8 star0)
(take_image satellite2 phenomenon8 instrument17 infrared5)
(turn_to satellite2 planet13 phenomenon8)
(take_image satellite2 planet13 instrument17 infrared5)
(turn_to satellite2 planet18 planet13)
(take_image satellite2 planet18 instrument17 infrared5)
(turn_to satellite2 planet7 planet18)
(take_image satellite2 planet7 instrument17 infrared5)
(turn_to satellite2 star24 planet7)
(take_image satellite2 star24 instrument17 infrared5)
