(switch_on instrument2 satellite0)
(switch_on instrument4 satellite1)
(switch_on instrument6 satellite2)
(switch_on instrument7 satellite3)
(switch_on instrument8 satellite4)
(turn_to satellite0 phenomenon7 star0)
(turn_to satellite1 phenomenon6 planet11)
(turn_to satellite0 star2 phenomenon7)
(calibrate satellite0 instrument2 star2)
(turn_to satellite0 phenomenon7 star2)
(turn_to satellite0 phenomenon8 phenomenon7)
(take_image satellite0 phenomenon8 instrument2 image2)
(turn_to satellite0 phenomenon7 phenomenon8)
(turn_to satellite0 planet5 phenomenon7)
(take_image satellite0 planet5 instrument2 image2)
(turn_to satellite0 phenomenon7 planet5)
(turn_to satellite2 phenomenon13 phenomenon6)
(turn_to satellite1 star3 phenomenon6)
(calibrate satellite1 instrument4 star3)
(turn_to satellite1 phenomenon12 star3)
(take_image satellite1 phenomenon12 instrument4 image3)
(turn_to satellite1 phenomenon6 phenomenon12)
(take_image satellite1 phenomenon6 instrument4 image3)
(turn_to satellite1 star9 phenomenon6)
(take_image satellite1 star9 instrument4 image3)
(turn_to satellite3 star0 planet10)
(calibrate satellite3 instrument7 star0)
(turn_to satellite3 phenomenon13 star0)
(take_image satellite3 phenomenon13 instrument7 spectrograph0)
(turn_to satellite3 planet10 phenomenon13)
(take_image satellite3 planet10 instrument7 image4)
(turn_to satellite3 planet11 planet10)
(take_image satellite3 planet11 instrument7 spectrograph0)
(turn_to satellite3 star14 planet11)
(take_image satellite3 star14 instrument7 image4)
(turn_to satellite3 star9 star14)
(turn_to satellite4 groundstation1 star9)
(calibrate satellite4 instrument8 groundstation1)
(turn_to satellite4 phenomenon7 groundstation1)
(take_image satellite4 phenomenon7 instrument8 infrared1)
(turn_to satellite4 planet5 phenomenon7)
