(switch_on instrument0 satellite0)
(switch_on instrument10 satellite2)
(switch_on instrument16 satellite3)
(switch_on instrument24 satellite4)
(switch_on instrument3 satellite1)
(turn_to satellite0 phenomenon11 planet21)
(turn_to satellite0 phenomenon13 phenomenon11)
(turn_to satellite3 phenomenon24 phenomenon20)
(turn_to satellite0 groundstation0 phenomenon13)
(calibrate satellite0 instrument0 groundstation0)
(turn_to satellite0 phenomenon11 groundstation0)
(take_image satellite0 phenomenon11 instrument0 infrared2)
(turn_to satellite0 phenomenon13 phenomenon11)
(take_image satellite0 phenomenon13 instrument0 infrared2)
(turn_to satellite0 phenomenon5 phenomenon13)
(take_image satellite0 phenomenon5 instrument0 image4)
(turn_to satellite0 planet15 phenomenon5)
(take_image satellite0 planet15 instrument0 infrared2)
(turn_to satellite0 planet17 planet15)
(take_image satellite0 planet17 instrument0 image4)
(turn_to satellite0 planet22 planet17)
(take_image satellite0 planet22 instrument0 infrared2)
(turn_to satellite0 planet17 planet22)
(turn_to satellite0 star14 planet17)
(take_image satellite0 star14 instrument0 infrared2)
(turn_to satellite0 planet17 star14)
(turn_to satellite0 star16 planet17)
(take_image satellite0 star16 instrument0 image4)
(turn_to satellite0 planet17 star16)
(turn_to satellite0 star18 planet17)
(take_image satellite0 star18 instrument0 infrared2)
(turn_to satellite0 planet17 star18)
(turn_to satellite0 star23 planet17)
(take_image satellite0 star23 instrument0 infrared2)
(turn_to satellite0 planet17 star23)
(turn_to satellite1 phenomenon7 planet21)
(turn_to satellite1 star1 phenomenon7)
(calibrate satellite1 instrument3 star1)
(turn_to satellite1 phenomenon24 star1)
(take_image satellite1 phenomenon24 instrument3 image5)
(turn_to satellite1 phenomenon7 phenomenon24)
(take_image satellite1 phenomenon7 instrument3 thermograph1)
(turn_to satellite1 planet17 phenomenon7)
(take_image satellite1 planet17 instrument3 image5)
(turn_to satellite1 planet21 planet17)
(take_image satellite1 planet21 instrument3 image5)
(turn_to satellite1 star12 planet21)
(take_image satellite1 star12 instrument3 thermograph1)
(turn_to satellite1 star19 star12)
(take_image satellite1 star19 instrument3 thermograph1)
(turn_to satellite2 groundstation4 phenomenon5)
(calibrate satellite2 instrument10 groundstation4)
(turn_to satellite2 phenomenon13 groundstation4)
(take_image satellite2 phenomenon13 instrument10 infrared7)
(turn_to satellite2 phenomenon5 phenomenon13)
(take_image satellite2 phenomenon5 instrument10 infrared7)
(turn_to satellite4 groundstation0 star14)
(calibrate satellite4 instrument24 groundstation0)
(turn_to satellite4 phenomenon20 groundstation0)
(take_image satellite4 phenomenon20 instrument24 spectrograph0)
(turn_to satellite4 planet21 phenomenon20)
(take_image satellite4 planet21 instrument24 infrared3)
(turn_to satellite4 planet9 planet21)
(take_image satellite4 planet9 instrument24 spectrograph0)
(turn_to satellite4 star10 planet9)
(take_image satellite4 star10 instrument24 infrared3)
(turn_to satellite4 star19 star10)
(take_image satellite4 star19 instrument24 infrared3)
(turn_to satellite3 planet9 phenomenon24)
(turn_to satellite3 star10 planet9)
(turn_to satellite3 star2 star10)
(calibrate satellite3 instrument16 star2)
(turn_to satellite3 phenomenon24 star2)
(take_image satellite3 phenomenon24 instrument16 spectrograph6)
(turn_to satellite3 planet9 phenomenon24)
(take_image satellite3 planet9 instrument16 spectrograph6)
(turn_to satellite3 star10 planet9)
(take_image satellite3 star10 instrument16 spectrograph6)
(turn_to satellite3 star12 star10)
(take_image satellite3 star12 instrument16 spectrograph6)
