(switch_on instrument10 satellite4)
(switch_on instrument3 satellite1)
(calibrate satellite1 instrument3 star4)
(switch_on instrument7 satellite3)
(turn_to satellite1 planet10 star4)
(take_image satellite1 planet10 instrument3 infrared3)
(turn_to satellite1 planet9 planet10)
(take_image satellite1 planet9 instrument3 infrared0)
(turn_to satellite1 star6 planet9)
(take_image satellite1 star6 instrument3 infrared3)
(turn_to satellite3 phenomenon14 groundstation3)
(turn_to satellite4 phenomenon13 planet10)
(turn_to satellite4 star0 phenomenon13)
(calibrate satellite4 instrument10 star0)
(turn_to satellite4 phenomenon13 star0)
(take_image satellite4 phenomenon13 instrument10 image4)
(turn_to satellite4 phenomenon8 phenomenon13)
(take_image satellite4 phenomenon8 instrument10 image4)
(turn_to satellite4 planet5 phenomenon8)
(take_image satellite4 planet5 instrument10 image4)
(turn_to satellite4 planet9 planet5)
(turn_to satellite3 star4 phenomenon14)
(calibrate satellite3 instrument7 star4)
(turn_to satellite3 phenomenon14 star4)
(take_image satellite3 phenomenon14 instrument7 spectrograph1)
(turn_to satellite3 star12 phenomenon14)
(take_image satellite3 star12 instrument7 image4)
(turn_to satellite3 star15 star12)
(take_image satellite3 star15 instrument7 spectrograph1)
(turn_to satellite3 star7 star15)
(take_image satellite3 star7 instrument7 image4)
(turn_to satellite4 star16 planet9)
(take_image satellite4 star16 instrument10 image2)
(turn_to satellite4 planet9 star16)
