(switch_on instrument0 satellite0)
(switch_on instrument3 satellite1)
(switch_on instrument7 satellite3)
(calibrate satellite3 instrument7 groundstation4)
(turn_to satellite0 groundstation2 phenomenon12)
(calibrate satellite0 instrument0 groundstation2)
(turn_to satellite0 phenomenon12 groundstation2)
(take_image satellite0 phenomenon12 instrument0 thermograph0)
(turn_to satellite0 phenomenon13 phenomenon12)
(take_image satellite0 phenomenon13 instrument0 image1)
(turn_to satellite0 phenomenon18 phenomenon13)
(take_image satellite0 phenomenon18 instrument0 image1)
(turn_to satellite0 phenomenon5 phenomenon18)
(take_image satellite0 phenomenon5 instrument0 image1)
(turn_to satellite0 phenomenon7 phenomenon5)
(take_image satellite0 phenomenon7 instrument0 thermograph0)
(turn_to satellite0 planet21 phenomenon7)
(take_image satellite0 planet21 instrument0 thermograph0)
(turn_to satellite0 planet23 planet21)
(take_image satellite0 planet23 instrument0 image1)
(turn_to satellite0 planet21 planet23)
(turn_to satellite1 groundstation2 groundstation1)
(calibrate satellite1 instrument3 groundstation2)
(turn_to satellite1 planet15 groundstation2)
(take_image satellite1 planet15 instrument3 image2)
(turn_to satellite1 planet17 planet15)
(take_image satellite1 planet17 instrument3 image2)
(turn_to satellite1 star14 planet17)
(take_image satellite1 star14 instrument3 thermograph4)
(turn_to satellite1 star19 star14)
(take_image satellite1 star19 instrument3 thermograph4)
(turn_to satellite1 star20 star19)
(take_image satellite1 star20 instrument3 thermograph4)
(turn_to satellite1 star9 star20)
(take_image satellite1 star9 instrument3 thermograph0)
(turn_to satellite2 star14 groundstation2)
(turn_to satellite3 planet8 groundstation4)
(take_image satellite3 planet8 instrument7 image2)
(turn_to satellite3 star10 planet8)
(take_image satellite3 star10 instrument7 thermograph3)
(turn_to satellite3 star22 star10)
(take_image satellite3 star22 instrument7 thermograph3)
(turn_to satellite5 planet17 phenomenon11)
