(switch_on instrument1 satellite0)
(switch_on instrument3 satellite1)
(switch_on instrument9 satellite3)
(turn_to satellite0 star2 phenomenon14)
(calibrate satellite0 instrument1 star2)
(turn_to satellite0 phenomenon13 star2)
(take_image satellite0 phenomenon13 instrument1 thermograph1)
(turn_to satellite0 phenomenon14 phenomenon13)
(take_image satellite0 phenomenon14 instrument1 thermograph2)
(turn_to satellite0 phenomenon5 phenomenon14)
(take_image satellite0 phenomenon5 instrument1 thermograph1)
(turn_to satellite0 star10 phenomenon5)
(take_image satellite0 star10 instrument1 spectrograph3)
(turn_to satellite0 star6 star10)
(take_image satellite0 star6 instrument1 thermograph1)
(turn_to satellite0 planet11 star6)
(take_image satellite0 planet11 instrument1 thermograph2)
(turn_to satellite0 star7 planet11)
(take_image satellite0 star7 instrument1 spectrograph3)
(turn_to satellite1 groundstation1 star4)
(calibrate satellite1 instrument3 groundstation1)
(turn_to satellite1 phenomenon12 groundstation1)
(take_image satellite1 phenomenon12 instrument3 image0)
(turn_to satellite1 phenomenon8 phenomenon12)
(take_image satellite1 phenomenon8 instrument3 image0)
(turn_to satellite1 phenomenon9 phenomenon8)
(take_image satellite1 phenomenon9 instrument3 image0)
