(switch_on instrument1 satellite1)
(switch_on instrument10 satellite4)
(switch_on instrument15 satellite7)
(switch_on instrument17 satellite8)
(turn_to satellite1 phenomenon14 planet5)
(turn_to satellite1 star3 phenomenon14)
(calibrate satellite1 instrument1 star3)
(turn_to satellite1 phenomenon15 star3)
(take_image satellite1 phenomenon15 instrument1 infrared2)
(turn_to satellite1 phenomenon14 phenomenon15)
(take_image satellite1 phenomenon14 instrument1 infrared2)
(turn_to satellite1 planet16 phenomenon14)
(take_image satellite1 planet16 instrument1 infrared2)
(turn_to satellite1 planet5 planet16)
(take_image satellite1 planet5 instrument1 image0)
(turn_to satellite1 star22 planet5)
(turn_to satellite4 phenomenon20 star22)
(turn_to satellite4 star3 phenomenon20)
(calibrate satellite4 instrument10 star3)
(turn_to satellite4 phenomenon20 star3)
(turn_to satellite4 phenomenon9 phenomenon20)
(take_image satellite4 phenomenon9 instrument10 image4)
(turn_to satellite4 phenomenon20 phenomenon9)
(turn_to satellite4 planet11 phenomenon20)
(take_image satellite4 planet11 instrument10 image4)
(turn_to satellite4 phenomenon20 planet11)
(turn_to satellite4 planet6 phenomenon20)
(take_image satellite4 planet6 instrument10 image4)
(turn_to satellite4 phenomenon20 planet6)
(turn_to satellite4 planet7 phenomenon20)
(take_image satellite4 planet7 instrument10 image4)
(turn_to satellite4 phenomenon20 planet7)
(turn_to satellite4 star18 phenomenon20)
(take_image satellite4 star18 instrument10 image4)
(turn_to satellite4 phenomenon20 star18)
(turn_to satellite4 star22 phenomenon20)
(take_image satellite4 star22 instrument10 image4)
(turn_to satellite4 phenomenon20 star22)
(turn_to satellite7 groundstation4 planet12)
(calibrate satellite7 instrument15 groundstation4)
(turn_to satellite7 phenomenon17 groundstation4)
(take_image satellite7 phenomenon17 instrument15 thermograph1)
(turn_to satellite7 planet12 phenomenon17)
(take_image satellite7 planet12 instrument15 thermograph1)
(turn_to satellite7 star10 planet12)
(take_image satellite7 star10 instrument15 thermograph1)
(turn_to satellite7 star21 star10)
(take_image satellite7 star21 instrument15 thermograph1)
(turn_to satellite8 groundstation0 phenomenon23)
(calibrate satellite8 instrument17 groundstation0)
(turn_to satellite8 phenomenon23 groundstation0)
(take_image satellite8 phenomenon23 instrument17 infrared3)
(turn_to satellite8 phenomenon24 phenomenon23)
(take_image satellite8 phenomenon24 instrument17 infrared3)
(turn_to satellite8 planet13 phenomenon24)
(take_image satellite8 planet13 instrument17 infrared3)
(turn_to satellite8 planet16 planet13)
