(switch_on instrument1 satellite0)
(switch_on instrument2 satellite1)
(switch_on instrument3 satellite2)
(switch_on instrument6 satellite4)
(turn_to satellite0 planet10 star19)
(turn_to satellite0 planet23 planet10)
(turn_to satellite0 planet25 planet23)
(turn_to satellite1 groundstation3 planet17)
(calibrate satellite1 instrument2 groundstation3)
(turn_to satellite0 groundstation3 planet25)
(calibrate satellite0 instrument1 groundstation3)
(turn_to satellite0 phenomenon27 groundstation3)
(take_image satellite0 phenomenon27 instrument1 thermograph1)
(turn_to satellite0 phenomenon5 phenomenon27)
(take_image satellite0 phenomenon5 instrument1 thermograph1)
(turn_to satellite0 planet10 phenomenon5)
(take_image satellite0 planet10 instrument1 thermograph1)
(turn_to satellite0 planet13 planet10)
(take_image satellite0 planet13 instrument1 thermograph1)
(turn_to satellite0 planet17 planet13)
(take_image satellite0 planet17 instrument1 image4)
(turn_to satellite0 planet23 planet17)
(take_image satellite0 planet23 instrument1 thermograph1)
(turn_to satellite0 planet25 planet23)
(take_image satellite0 planet25 instrument1 thermograph1)
(turn_to satellite0 star21 planet25)
(take_image satellite0 star21 instrument1 thermograph1)
(turn_to satellite0 star22 star21)
(take_image satellite0 star22 instrument1 image4)
(turn_to satellite1 phenomenon5 groundstation3)
(turn_to satellite1 planet11 phenomenon5)
(take_image satellite1 planet11 instrument2 thermograph2)
(turn_to satellite1 phenomenon5 planet11)
(turn_to satellite1 planet15 phenomenon5)
(take_image satellite1 planet15 instrument2 thermograph0)
(turn_to satellite1 phenomenon5 planet15)
(turn_to satellite1 planet24 phenomenon5)
(take_image satellite1 planet24 instrument2 thermograph2)
(turn_to satellite1 phenomenon5 planet24)
(turn_to satellite1 planet28 phenomenon5)
(take_image satellite1 planet28 instrument2 thermograph2)
(turn_to satellite1 phenomenon5 planet28)
(turn_to satellite1 planet29 phenomenon5)
(take_image satellite1 planet29 instrument2 thermograph0)
(turn_to satellite1 phenomenon5 planet29)
(turn_to satellite1 planet6 phenomenon5)
(take_image satellite1 planet6 instrument2 image4)
(turn_to satellite1 phenomenon5 planet6)
(turn_to satellite1 planet9 phenomenon5)
(take_image satellite1 planet9 instrument2 thermograph0)
(turn_to satellite1 phenomenon5 planet9)
(turn_to satellite1 star19 phenomenon5)
(take_image satellite1 star19 instrument2 thermograph0)
(turn_to satellite1 phenomenon5 star19)
(turn_to satellite1 star26 phenomenon5)
(take_image satellite1 star26 instrument2 thermograph0)
(turn_to satellite1 phenomenon5 star26)
(turn_to satellite2 star1 planet7)
(calibrate satellite2 instrument3 star1)
(turn_to satellite2 phenomenon12 star1)
(take_image satellite2 phenomenon12 instrument3 image3)
(turn_to satellite2 phenomenon18 phenomenon12)
(take_image satellite2 phenomenon18 instrument3 image3)
(turn_to satellite2 planet11 phenomenon18)
(turn_to satellite2 planet16 planet11)
(take_image satellite2 planet16 instrument3 image3)
(turn_to satellite2 planet11 planet16)
(turn_to satellite2 planet7 planet11)
(take_image satellite2 planet7 instrument3 image3)
(turn_to satellite2 planet11 planet7)
(turn_to satellite2 planet8 planet11)
(take_image satellite2 planet8 instrument3 image3)
(turn_to satellite2 planet11 planet8)
(turn_to satellite2 star14 planet11)
(take_image satellite2 star14 instrument3 image3)
(turn_to satellite2 planet11 star14)
(turn_to satellite4 planet11 phenomenon5)
